<?php

namespace Database\Seeders;

use App\Models\LlmModel;
use Illuminate\Database\Seeder;

class LlmModelSeeder extends Seeder
{
    public function run(): void
    {
        $models = [
            // Bulgarian / General Text
            ['ollama_tag' => 'todorov/bggpt',              'display_name' => 'BgGPT 3.0',           'category' => 'bulgarian',    'description' => 'INSAIT BgGPT 3.0, базиран на Gemma 3 от Google. Поддържа мултимодален вход (текст + изображения), контекст до 128K токена и е оптимизиран специално за български. Идеален когато трябва да разбираш изображения заедно с текстова обработка на кирилица.', 'strengths' => ['bulgarian_text', 'natural_bg_language', 'multimodal', 'vision', 'long_context'], 'ram_required_gb' => 10.0, 'size_mb' => 9000,  'is_default_for' => ['content_bg', 'summarizer']],
            ['ollama_tag' => 's_emanuilov/BgGPT-v1.0:2.6b', 'display_name' => 'BgGPT v1.0 2.6B',    'category' => 'qa',           'description' => 'Лекият INSAIT BgGPT модел (2.6B параметъра), специализиран за бързи проверки и кратки задачи на български. Работи дори на слаб хардуер — перфектен за QA верификатор и автоматизирано публикуване, когато скоростта е по-важна от дълбочината.',        'strengths' => ['bulgarian_text', 'fast', 'qa', 'natural_bg_language'], 'ram_required_gb' => 2.5,  'size_mb' => 1700,  'is_default_for' => ['qa_verifier', 'publisher']],
            ['ollama_tag' => 's_emanuilov/BgGPT-v1.0:9b',  'display_name' => 'BgGPT v1.0 9B',      'category' => 'bulgarian',    'description' => 'State-of-the-art български езиков модел от INSAIT, базиран на Gemma 2 9B. Балансира качество и скорост за всички задачи на кирилица — писане на съдържание, SEO, имейли, реклами, описания и преводи. Препоръчителен основен избор за всякакво съдържание на български.',  'strengths' => ['bulgarian_text', 'natural_bg_language', 'powerful'],  'ram_required_gb' => 8.0,  'size_mb' => 6000,  'is_default_for' => ['content_bg', 'seo_writer', 'newsletter_writer', 'report_writer', 'email_composer', 'ad_copywriter', 'offer_builder', 'caption_writer', 'hook_writer', 'faq_generator', 'meta_generator', 'summarizer', 'translator']],
            ['ollama_tag' => 's_emanuilov/BgGPT-v1.0:27b', 'display_name' => 'BgGPT v1.0 27B',     'category' => 'bulgarian',    'description' => 'Флагманският INSAIT BgGPT модел (27B параметъра) за максимално качество на български текст. Изисква 20 GB RAM, но генерира премиум резултати — използвайте за официални документи, сложен маркетинг текст и случаи, където качеството е критично.',          'strengths' => ['bulgarian_text', 'natural_bg_language', 'premium_bulgarian', 'powerful'], 'ram_required_gb' => 20.0, 'size_mb' => 17000, 'is_default_for' => ['content_bg', 'seo_writer', 'newsletter_writer', 'report_writer', 'email_composer', 'ad_copywriter', 'offer_builder', 'caption_writer', 'hook_writer', 'faq_generator', 'meta_generator', 'summarizer', 'translator']],
            ['ollama_tag' => 'llama3.1:8b',      'display_name' => 'LLaMA 3.1 8B',   'category' => 'general',      'description' => 'Meta LLaMA 3.1 с 8B параметъра — отличен баланс между скорост и качество за английски текст. Бърз, надежден и универсален за съдържание, обобщения и общи задачи. Препоръчан за production workflows с умерен хардуер.',                   'strengths' => ['english_text', 'balanced', 'fast'],                   'ram_required_gb' => 5.0,  'size_mb' => 4700,  'is_default_for' => ['content_en', 'summarizer']],
            ['ollama_tag' => 'llama3.1:70b',     'display_name' => 'LLaMA 3.1 70B',  'category' => 'general',      'description' => 'Флагманският модел на Meta за максимално качество на английски. С 70B параметъра изисква сериозен GPU, но предоставя текстове на нивото на GPT-4. Използвайте за критично важни документи и висококачествено съдържание.',              'strengths' => ['high_quality_text', 'powerful'],                      'ram_required_gb' => 40.0, 'size_mb' => 39000, 'is_default_for' => ['content_en', 'report_writer', 'seo_writer', 'newsletter_writer', 'summarizer']],
            ['ollama_tag' => 'llama3.2:3b',      'display_name' => 'LLaMA 3.2 3B',   'category' => 'general',      'description' => 'Ултра компактна версия на LLaMA 3.2 (3B параметъра). Работи без GPU и отговаря светкавично бързо. Подходящ само за прости, кратки задачи — не за сложно съдържание или анализи.',                                             'strengths' => ['ultra_fast', 'simple_tasks'],                         'ram_required_gb' => 2.0,  'size_mb' => 2000,  'is_default_for' => ['qa_verifier', 'publisher']],
            ['ollama_tag' => 'gemma3:12b',       'display_name' => 'Gemma 3 12B',     'category' => 'general',      'description' => 'Google Gemma 3 с 12B параметъра — ново поколение модел с 128K контекст и мултимодален вход (текст + изображения). Превъзхожда по-старите модели в следването на инструкции. Универсален избор за разнообразни задачи с дълги документи.',                    'strengths' => ['128k_context', 'multimodal', 'high_quality'],         'ram_required_gb' => 10.0, 'size_mb' => 8100,  'is_default_for' => ['summarizer', 'analyzer', 'content_en', 'image_describer']],
            ['ollama_tag' => 'gemma2:9b',        'display_name' => 'Gemma 2 9B',      'category' => 'general',      'description' => 'Google Gemma 2 9B — отличен за structured output, JSON генериране и детайлни анализи. Надежден при следване на схеми и формати. Добре се справя с кирилица, подходящ за класификации и извличане на данни.',                     'strengths' => ['structured_output', 'analysis'],                      'ram_required_gb' => 6.0,  'size_mb' => 5400,  'is_default_for' => ['data_extractor', 'classifier', 'formatter', 'analyzer']],
            ['ollama_tag' => 'gemma2:27b',       'display_name' => 'Gemma 2 27B',     'category' => 'general',      'description' => 'По-мощната версия на Gemma 2 с 27B параметъра. Значително по-добър при сложни reasoning задачи и генериране на дълги структурирани отговори. Изисква 16 GB RAM — препоръчан за premium анализи.',                                               'strengths' => ['structured_output', 'powerful'],                      'ram_required_gb' => 16.0, 'size_mb' => 15800, 'is_default_for' => ['analyzer', 'swot_builder', 'data_extractor']],
            ['ollama_tag' => 'gemma4',           'display_name' => 'Gemma 4 E4B',     'category' => 'general',      'description' => 'Google Gemma 4 E4B (март 2026) — ново поколение с native tool calling, thinking режим и мултимодален вход (текст + изображения) при 128K контекст. MatFormer архитектура с ~4B активни параметъра — бърз въпреки размера си. Отличен за агентни задачи, structured output и tool use.', 'strengths' => ['native_tool_calling', 'thinking', 'multimodal', '128k_context', 'agentic'], 'ram_required_gb' => 10.0, 'size_mb' => 9600, 'is_default_for' => ['orchestrator', 'decision', 'analyzer']],

            // JSON / Instructions
            ['ollama_tag' => 'mistral',          'display_name' => 'Mistral 7B',      'category' => 'json',         'description' => 'Mistral 7B е еталон за JSON генериране и прецизно следване на инструкции. Многократно верифициран за задачи, изискващи строг формат на изход. Идеален за оркестратор и генериране на image prompt-ове, където форматът на отговора е критичен.',                          'strengths' => ['json_output', 'instruction_following', 'structured'], 'ram_required_gb' => 4.0,  'size_mb' => 4100,  'is_default_for' => ['image_prompt', 'orchestrator']],
            ['ollama_tag' => 'mistral-nemo',     'display_name' => 'Mistral NeMo 12B', 'category' => 'json',         'description' => 'По-мощният наследник на Mistral 7B с 12B параметъра. Превъзхождащ при агентни задачи, по-дълги контексти и complex tool use. Когато Mistral 7B не е достатъчен за сложността на задачата, NeMo е следващата стъпка.',                                'strengths' => ['json_output', 'agent_tasks'],                         'ram_required_gb' => 7.0,  'size_mb' => 7100,  'is_default_for' => ['orchestrator', 'decision', 'researcher']],
            ['ollama_tag' => 'mixtral:8x7b',     'display_name' => 'Mixtral 8x7B',    'category' => 'json',         'description' => 'Mixture-of-Experts архитектура — активира само 2 от 8 експертни модула при всяка генерация. Качеството на 45B модел при потребление на ресурси като 13B. Изисква 26 GB RAM — за сървъри с повече оперативна памет.',                                    'strengths' => ['high_quality', 'moe_architecture'],                   'ram_required_gb' => 26.0, 'size_mb' => 26100, 'is_default_for' => ['analyzer', 'researcher', 'content_en']],
            ['ollama_tag' => 'qwen2.5:7b',       'display_name' => 'Qwen2.5 7B',      'category' => 'json',         'description' => 'Alibaba Qwen2.5 7B — специализиран за structured tasks, JSON output и многоезично съдържание на 29 езика вкл. български. Надежден за автоматизирани pipeline задачи: извличане на данни, ключови думи, хаштагове и форматиране.',                     'strengths' => ['structured_tasks', 'multilingual'],                   'ram_required_gb' => 5.0,  'size_mb' => 4700,  'is_default_for' => ['keyword_extractor', 'hashtag_generator', 'data_extractor', 'formatter', 'google_sheets_writer', 'email', 'webhook_sender', 'slack_notifier', 'content_en']],
            ['ollama_tag' => 'qwen2.5:14b',      'display_name' => 'Qwen2.5 14B',     'category' => 'json',         'description' => 'По-мощна версия на Qwen2.5 с отлично разбиране на кирилица и JSON архитектура. Топ избор под 15 GB RAM за анализи, вземане на решения, SWOT, класификации и изследване на конкуренти. Препоръчан оркестратор за сложни multi-agent flows.', 'strengths' => ['structured_tasks', 'powerful', 'reasoning', 'cyrillic'], 'ram_required_gb' => 9.0,  'size_mb' => 9000,  'is_default_for' => ['analyzer', 'decision', 'swot_builder', 'sentiment_analyzer', 'classifier', 'review_analyzer', 'researcher', 'trend_researcher', 'competitor_profiler', 'orchestrator']],

            // Reasoning / Analysis
            ['ollama_tag' => 'deepseek-r1:8b',   'display_name' => 'DeepSeek-R1 8B',  'category' => 'reasoning',    'description' => 'DeepSeek-R1 с chain-of-thought reasoning — моделът "мисли" на глас преди да отговори. Видимите стъпки на разсъждение правят изводите прозрачни и проверими. Компактен вариант за анализи и вземане на решения при ограничен RAM.',           'strengths' => ['reasoning', 'analysis', 'chain_of_thought'],          'ram_required_gb' => 5.0,  'size_mb' => 4900,  'is_default_for' => ['analyzer', 'decision']],
            ['ollama_tag' => 'deepseek-r1:32b',  'display_name' => 'DeepSeek-R1 32B', 'category' => 'reasoning',    'description' => 'Разширеният DeepSeek-R1 модел с 32B параметъра. Значително по-дълбоко chain-of-thought reasoning за сложни бизнес проблеми, многостъпкови анализи и стратегически решения. Изисква 20 GB RAM.',                                                 'strengths' => ['reasoning', 'powerful'],                              'ram_required_gb' => 20.0, 'size_mb' => 19400, 'is_default_for' => ['analyzer', 'decision', 'swot_builder', 'researcher', 'competitor_profiler']],
            ['ollama_tag' => 'qwq:32b',          'display_name' => 'QwQ 32B',          'category' => 'reasoning',    'description' => 'Alibaba reasoning модел с 32B параметъра, специализиран за размишление върху сложни проблеми. Отличен за multi-step задачи, математически разсъждения и ситуации с много взаимосвързани фактори. Конкурент на DeepSeek-R1 32B.',                      'strengths' => ['reasoning', 'complex_decisions'],                     'ram_required_gb' => 20.0, 'size_mb' => 19400, 'is_default_for' => ['analyzer', 'decision', 'researcher']],
            ['ollama_tag' => 'phi4',             'display_name' => 'Phi-4 14B',        'category' => 'reasoning',    'description' => 'Microsoft Phi-4 с 14B параметъра постига резултати на по-големи модели благодарение на висококачествени training данни. Отличен reasoning при само 9 GB RAM — ефективен избор когато ресурсите са ограничени, но качеството е важно.',                       'strengths' => ['reasoning', 'efficient'],                             'ram_required_gb' => 9.0,  'size_mb' => 8500,  'is_default_for' => ['analyzer', 'decision', 'summarizer']],
            ['ollama_tag' => 'deepseek-r1:14b', 'display_name' => 'DeepSeek-R1 14B',  'category' => 'reasoning',    'description' => 'Балансираният DeepSeek-R1 модел — по-мощен от 8B, по-достъпен от 32B. Изчерпателно chain-of-thought reasoning при 11 GB RAM. Препоръчан като основен reasoning модел за повечето production flows.',                          'strengths' => ['reasoning', 'chain_of_thought', 'powerful'],          'ram_required_gb' => 11.0, 'size_mb' => 9000,  'is_default_for' => ['analyzer', 'decision', 'researcher', 'trend_researcher']],
            ['ollama_tag' => 'phi4-reasoning',  'display_name' => 'Phi-4 Reasoning',  'category' => 'reasoning',    'description' => 'Microsoft Phi-4 Reasoning — специализирана версия, финно настроена изцяло за reasoning задачи. Съперничи на модели 2-3 пъти по-големи в бенчмаркове за логика и планиране. Идеален за вземане на решения при ограничени GPU ресурси.',   'strengths' => ['reasoning', 'specialized', 'efficient'],             'ram_required_gb' => 11.0, 'size_mb' => 9100,  'is_default_for' => ['decision', 'analyzer', 'swot_builder']],

            // QA / Verification
            ['ollama_tag' => 'phi3:mini',        'display_name' => 'Phi-3 Mini',       'category' => 'qa',           'description' => 'Microsoft Phi-3 Mini с 3.8B параметъра — ултра бърз за верификация на кратко съдържание. Работи на почти всеки хардуер. Подходящ като publisher — финален преглед преди публикуване, без тежки ресурси.',                               'strengths' => ['fast', 'qa', 'simple_tasks'],                         'ram_required_gb' => 2.0,  'size_mb' => 2300,  'is_default_for' => ['publisher']],
            ['ollama_tag' => 'phi3.5',           'display_name' => 'Phi-3.5 Mini 3.8B', 'category' => 'qa',         'description' => 'Подобрена версия на Phi-3 Mini с по-добро следване на инструкции. Леко по-бавен от оригинала, но по-точен при структурирани QA задачи и форматиране. Подходящ когато Phi-3 Mini прави грешки при по-сложно форматиране.',                       'strengths' => ['fast', 'qa', 'improved'],                             'ram_required_gb' => 2.5,  'size_mb' => 2200,  'is_default_for' => ['qa_verifier', 'publisher']],
            ['ollama_tag' => 'gemma2:2b',        'display_name' => 'Gemma 2 2B',       'category' => 'qa',           'description' => 'Google Gemma 2 с 2B параметъра — един от най-бързите достъпни модели. За прости boolean проверки, кратко форматиране и задачи, изискващи минимален отговор. Не е подходящ за генериране на сложно съдържание.',                                     'strengths' => ['fast', 'simple_tasks'],                               'ram_required_gb' => 2.0,  'size_mb' => 1600,  'is_default_for' => ['qa_verifier']],
            ['ollama_tag' => 'llama3.2:1b',      'display_name' => 'LLaMA 3.2 1B',    'category' => 'qa',           'description' => 'Най-малкият наличен модел (1B параметъра) — отговаря за секунди дори без GPU. Само за елементарни QA проверки: дали текстът е на правилен език, дали форматът е верен. Не замества по-способни модели.',                                     'strengths' => ['lightest', 'simple_qa'],                              'ram_required_gb' => 1.0,  'size_mb' => 1300,  'is_default_for' => ['qa_verifier']],

            // Code
            ['ollama_tag' => 'deepseek-coder-v2', 'display_name' => 'DeepSeek Coder V2', 'category' => 'code',        'description' => 'Водещ open-source модел за генериране на код — поддържа над 300 езика за програмиране с изключително прецизно разбиране на контекста. Препоръчан по подразбиране за всички задачи, свързани с генериране, преглед и дебъгване на код.',                                              'strengths' => ['code_generation', 'top_coder'],                       'ram_required_gb' => 9.0,  'size_mb' => 8900,  'is_default_for' => ['code']],
            ['ollama_tag' => 'qwen2.5-coder:7b',  'display_name' => 'Qwen2.5 Coder 7B', 'category' => 'code',        'description' => 'Alibaba специализиран coding модел с 7B параметъра. Бърз при генериране на boilerplate код и кратки функции. Добър избор когато скоростта е важна — SQL заявки, HTML шаблони, прости скриптове.',                                               'strengths' => ['code_generation', 'fast'],                            'ram_required_gb' => 5.0,  'size_mb' => 4700,  'is_default_for' => ['code']],
            ['ollama_tag' => 'qwen2.5-coder:14b', 'display_name' => 'Qwen2.5 Coder 14B', 'category' => 'code',       'description' => 'Най-популярният open-source code модел (над 16 млн. изтегляния). С 14B параметъра предоставя отличен code reasoning — разбира архитектурата на проекта, рефакторира и обяснява сложен код. Топ избор за code review и сложни задачи.',             'strengths' => ['code_generation', 'code_reasoning', 'popular'],       'ram_required_gb' => 11.0, 'size_mb' => 9000,  'is_default_for' => ['code']],
            ['ollama_tag' => 'codellama:13b',    'display_name' => 'CodeLlama 13B',    'category' => 'code',        'description' => 'Meta CodeLlama 13B, специализиран за code completion в стила на GitHub Copilot. Особено добър при довършване на частично написан код и следване на съществуващи coding стилове. По-малко ефективен от Qwen2.5 Coder при генериране на нов код.',                                           'strengths' => ['code_completion'],                                    'ram_required_gb' => 8.0,  'size_mb' => 7400,  'is_default_for' => ['code']],
            ['ollama_tag' => 'starcoder2:7b',    'display_name' => 'StarCoder2 7B',    'category' => 'code',        'description' => 'Hugging Face StarCoder2 с 7B параметъра — тренирани на The Stack v2, огромен корпус от open-source код. Добра алтернатива при по-малко RAM. По-слаб от Qwen2.5 Coder, но достатъчен за стандартни coding задачи.',                                       'strengths' => ['code_tasks'],                                         'ram_required_gb' => 4.0,  'size_mb' => 4000,  'is_default_for' => ['code']],

            // Multilingual
            ['ollama_tag' => 'qwen2:7b',         'display_name' => 'Qwen2 7B',         'category' => 'multilingual', 'description' => 'Alibaba Qwen2 с поддръжка на 29 езика и отличен multilingual performance. Специализиран за преводи и съдържание на езици извън английски — включително български. Препоръчан за translator и content_bg задачи.',                                           'strengths' => ['multilingual', '29_languages'],                       'ram_required_gb' => 5.0,  'size_mb' => 4400,  'is_default_for' => ['translator', 'content_bg']],
            ['ollama_tag' => 'aya:8b',           'display_name' => 'Aya 8B',           'category' => 'multilingual', 'description' => 'Cohere Aya с 8B параметъра, специализиран изцяло за многоезично съдържание на 23 езика. По-добро разбиране на нюансите в езика в сравнение с общите multilingual модели. Добра алтернатива на Qwen2 за преводи.',                                        'strengths' => ['multilingual', '23_languages'],                       'ram_required_gb' => 5.0,  'size_mb' => 4700,  'is_default_for' => ['translator']],
            ['ollama_tag' => 'aya-expanse:8b',   'display_name' => 'Aya Expanse 8B',   'category' => 'multilingual', 'description' => 'Подобрената версия на Aya с разширени езикови способности. Препоръчана замяна на оригиналния Aya 8B за по-качествени преводи и по-естествен текст на не-английски езици. Текущ препоръчан translator модел.',                                                    'strengths' => ['multilingual', 'improved_aya'],                       'ram_required_gb' => 5.0,  'size_mb' => 4700,  'is_default_for' => ['translator']],

            // Vision
            ['ollama_tag' => 'llava:7b',             'display_name' => 'LLaVA 7B',             'category' => 'vision', 'description' => 'LLaVA (Large Language and Vision Assistant) 7B — един от първите open-source мултимодални модели. Описва съдържанието на изображения, идентифицира обекти и отговаря на въпроси за снимки. Компактен за базова vision функционалност.',         'strengths' => ['image_analysis', 'vision'],        'ram_required_gb' => 5.0,  'size_mb' => 4700,  'is_default_for' => ['image_describer', 'vision']],
            ['ollama_tag' => 'llava:13b',            'display_name' => 'LLaVA 13B',            'category' => 'vision', 'description' => 'По-мощната версия на LLaVA с 13B параметъра. Значително по-добро разбиране на детайли в изображенията, пространствени отношения и извличане на текст (OCR). Препоръчан над 7B версията когато качеството на vision анализа е важно.',                  'strengths' => ['image_analysis', 'better_vision'], 'ram_required_gb' => 8.0,  'size_mb' => 7400,  'is_default_for' => ['image_describer', 'vision']],
            ['ollama_tag' => 'moondream',            'display_name' => 'Moondream 2',           'category' => 'vision', 'description' => 'Ултра лек vision модел (само 1.7 GB) за базово описание на изображения. Работи дори на лаптоп CPU. Подходящ единствено за прости задачи: "какво има на снимката" — не за детайлен анализ.',                'strengths' => ['ultra_light', 'vision'],            'ram_required_gb' => 2.0,  'size_mb' => 1700,  'is_default_for' => ['image_describer', 'vision']],
            ['ollama_tag' => 'llama3.2-vision:11b', 'display_name' => 'LLaMA 3.2 Vision 11B', 'category' => 'vision', 'description' => 'Meta LLaMA 3.2 Vision с 11B параметъра — най-добрият multilingual vision модел в класа. Разбира текст в изображения на множество езици, анализира диаграми и документи. Препоръчан за production vision задачи.',               'strengths' => ['vision', 'meta', 'high_quality'],  'ram_required_gb' => 8.0,  'size_mb' => 7900,  'is_default_for' => ['image_describer', 'vision']],
            ['ollama_tag' => 'qwen2.5vl:7b',        'display_name' => 'Qwen2.5 VL 7B',        'category' => 'vision', 'description' => 'Alibaba Qwen2.5 Vision-Language 7B — специализиран за OCR, документно разбиране и извличане на структурирани данни от изображения. Текущ препоръчан модел за image_describer задачи поради отличния му document understanding.', 'strengths' => ['vision', 'ocr', 'document_understanding'], 'ram_required_gb' => 7.0, 'size_mb' => 5000, 'is_default_for' => ['image_describer']],
        ];

        foreach ($models as $model) {
            LlmModel::updateOrCreate(
                ['ollama_tag' => $model['ollama_tag']],
                $model
            );
        }
    }
}
