<?php

namespace Database\Seeders;

use App\Models\LlmModel;
use Illuminate\Database\Seeder;

class LlmModelSeeder extends Seeder
{
    public function run(): void
    {
        $models = [
            // Bulgarian / General Text
            ['ollama_tag' => 'todorov/bggpt:Gemma-3-12B-IT-Q5_K_M', 'display_name' => 'BgGPT 3.0 12B', 'category' => 'bulgarian',    'description' => 'INSAIT BgGPT 3.0 12B, базиран на Gemma 3 — НАЙ-ДОБРИЯТ модел за български (бие Qwen3 235B на BG бенчмарковете). Мултимодален вход (текст + изображения), 128K контекст. Препоръчителен основен избор за всякакво съдържание и дълги доклади на български.', 'strengths' => ['bulgarian_text', 'natural_bg_language', 'premium_bulgarian', 'multimodal', 'vision', 'long_context', 'powerful'], 'ram_required_gb' => 10.0, 'size_mb' => 8400,  'is_default_for' => ['content_bg', 'seo_writer', 'newsletter_writer', 'report_writer', 'email_composer', 'ad_copywriter', 'offer_builder', 'caption_writer', 'hook_writer', 'faq_generator', 'meta_generator', 'summarizer', 'translator']],
            ['ollama_tag' => 'todorov/bggpt:Gemma-3-27B-IT-Q4_K_M', 'display_name' => 'BgGPT 3.0 27B', 'category' => 'bulgarian',    'description' => 'Флагманският INSAIT BgGPT 3.0 (27B, Gemma 3 база) за максимално качество на български — 128K контекст, мултимодален. Изисква ~20 GB и е бавен без голямо GPU; ползвайте за официални документи и критично съдържание, иначе 12B стига.', 'strengths' => ['bulgarian_text', 'natural_bg_language', 'premium_bulgarian', 'multimodal', 'long_context', 'powerful'], 'ram_required_gb' => 20.0, 'size_mb' => 17000, 'is_default_for' => ['content_bg', 'report_writer']],
            ['ollama_tag' => 's_emanuilov/BgGPT-v1.0:2.6b', 'display_name' => 'BgGPT v1.0 2.6B',    'category' => 'qa',           'description' => 'Лекият INSAIT BgGPT модел (2.6B параметъра), специализиран за бързи проверки и кратки задачи на български. Работи дори на слаб хардуер — перфектен за QA верификатор и автоматизирано публикуване, когато скоростта е по-важна от дълбочината.',        'strengths' => ['bulgarian_text', 'fast', 'qa', 'natural_bg_language'], 'ram_required_gb' => 2.5,  'size_mb' => 1700,  'is_default_for' => ['qa_verifier', 'publisher']],
            ['ollama_tag' => 's_emanuilov/BgGPT-v1.0:9b',  'display_name' => 'BgGPT v1.0 9B',      'category' => 'bulgarian',    'description' => 'State-of-the-art български езиков модел от INSAIT, базиран на Gemma 2 9B. Балансира качество и скорост за всички задачи на кирилица — писане на съдържание, SEO, имейли, реклами, описания и преводи. Препоръчителен основен избор за всякакво съдържание на български.',  'strengths' => ['bulgarian_text', 'natural_bg_language', 'powerful'],  'ram_required_gb' => 8.0,  'size_mb' => 6000,  'is_default_for' => ['content_bg', 'seo_writer', 'newsletter_writer', 'report_writer', 'email_composer', 'ad_copywriter', 'offer_builder', 'caption_writer', 'hook_writer', 'faq_generator', 'meta_generator', 'summarizer', 'translator']],
            ['ollama_tag' => 's_emanuilov/BgGPT-v1.0:27b', 'display_name' => 'BgGPT v1.0 27B',     'category' => 'bulgarian',    'description' => 'Флагманският INSAIT BgGPT модел (27B параметъра) за максимално качество на български текст. Изисква 20 GB RAM, но генерира премиум резултати — използвайте за официални документи, сложен маркетинг текст и случаи, където качеството е критично.',          'strengths' => ['bulgarian_text', 'natural_bg_language', 'premium_bulgarian', 'powerful'], 'ram_required_gb' => 20.0, 'size_mb' => 17000, 'is_default_for' => ['content_bg', 'seo_writer', 'newsletter_writer', 'report_writer', 'email_composer', 'ad_copywriter', 'offer_builder', 'caption_writer', 'hook_writer', 'faq_generator', 'meta_generator', 'summarizer', 'translator']],
            ['ollama_tag' => 'llama3.1:8b',      'display_name' => 'LLaMA 3.1 8B',   'category' => 'general',      'description' => 'Meta LLaMA 3.1 с 8B параметъра — отличен баланс между скорост и качество за английски текст. Бърз, надежден и универсален за съдържание, обобщения и общи задачи. Препоръчан за production workflows с умерен хардуер.',                   'strengths' => ['english_text', 'balanced', 'fast'],                   'ram_required_gb' => 5.0,  'size_mb' => 4700,  'is_default_for' => ['content_en', 'summarizer']],
            ['ollama_tag' => 'llama3.2:3b',      'display_name' => 'LLaMA 3.2 3B',   'category' => 'general',      'description' => 'Ултра компактна версия на LLaMA 3.2 (3B параметъра). Работи без GPU и отговаря светкавично бързо. Подходящ само за прости, кратки задачи — не за сложно съдържание или анализи.',                                             'strengths' => ['ultra_fast', 'simple_tasks'],                         'ram_required_gb' => 2.0,  'size_mb' => 2000,  'is_default_for' => ['qa_verifier', 'publisher']],
            ['ollama_tag' => 'gpt-oss:20b',      'display_name' => 'GPT-OSS 20B',    'category' => 'general',      'description' => 'OpenAI GPT-OSS 20B — open-weight MoE модел (3.6B активни параметъра) с настройваемо ниво на reasoning и native tool calling. Качество близо до o3-mini при само ~13 GB. Изисква 16 GB VRAM и Ollama ≥ 0.11 — НЕ е за 8 GB карти.', 'strengths' => ['reasoning', 'agentic', 'tool_calling', 'moe_architecture'], 'ram_required_gb' => 14.0, 'size_mb' => 13800, 'is_default_for' => ['analyzer', 'decision', 'researcher']],
            ['ollama_tag' => 'gemma4:12b',       'display_name' => 'Gemma 4 12B',     'category' => 'general',      'description' => 'Google Gemma 4 12B (юни 2026) — encoder-free мултимодален модел (текст + изображения) с 256K контекст, native tool calling и thinking режим. Доближава качеството на 26B варианта и бие Gemma 3 27B, а при Q4 (7.6 GB) се събира изцяло в 16 GB VRAM. Основен избор за анализи, structured output и агентни задачи.', 'strengths' => ['native_tool_calling', 'thinking', 'multimodal', '256k_context', 'agentic', 'structured_output'], 'ram_required_gb' => 10.0, 'size_mb' => 7600, 'is_default_for' => ['orchestrator', 'decision', 'analyzer', 'summarizer', 'content_en', 'image_describer', 'data_extractor', 'classifier', 'formatter', 'swot_builder']],

            // JSON / Instructions
            ['ollama_tag' => 'mistral',          'display_name' => 'Mistral 7B',      'category' => 'json',         'description' => 'Mistral 7B е еталон за JSON генериране и прецизно следване на инструкции. Многократно верифициран за задачи, изискващи строг формат на изход. Идеален за оркестратор и генериране на image prompt-ове, където форматът на отговора е критичен.',                          'strengths' => ['json_output', 'instruction_following', 'structured'], 'ram_required_gb' => 4.0,  'size_mb' => 4100,  'is_default_for' => ['image_prompt', 'orchestrator']],
            ['ollama_tag' => 'mistral-nemo',     'display_name' => 'Mistral NeMo 12B', 'category' => 'json',         'description' => 'По-мощният наследник на Mistral 7B с 12B параметъра. Превъзхождащ при агентни задачи, по-дълги контексти и complex tool use. Когато Mistral 7B не е достатъчен за сложността на задачата, NeMo е следващата стъпка.',                                'strengths' => ['json_output', 'agent_tasks'],                         'ram_required_gb' => 7.0,  'size_mb' => 7100,  'is_default_for' => ['orchestrator', 'decision', 'researcher']],
            ['ollama_tag' => 'qwen2.5:7b',       'display_name' => 'Qwen2.5 7B',      'category' => 'json',         'description' => 'Alibaba Qwen2.5 7B — специализиран за structured tasks, JSON output и многоезично съдържание на 29 езика вкл. български. Надежден за автоматизирани pipeline задачи: извличане на данни, ключови думи, хаштагове и форматиране.',                     'strengths' => ['structured_tasks', 'multilingual'],                   'ram_required_gb' => 5.0,  'size_mb' => 4700,  'is_default_for' => ['keyword_extractor', 'hashtag_generator', 'data_extractor', 'formatter', 'google_sheets_writer', 'email', 'webhook_sender', 'slack_notifier', 'content_en']],
            ['ollama_tag' => 'qwen2.5:14b',      'display_name' => 'Qwen2.5 14B',     'category' => 'json',         'description' => 'По-мощна версия на Qwen2.5 с отлично разбиране на кирилица и JSON архитектура. Топ избор под 15 GB RAM за анализи, вземане на решения, SWOT, класификации и изследване на конкуренти. Препоръчан оркестратор за сложни multi-agent flows.', 'strengths' => ['structured_tasks', 'powerful', 'reasoning', 'cyrillic'], 'ram_required_gb' => 9.0,  'size_mb' => 9000,  'is_default_for' => ['analyzer', 'decision', 'swot_builder', 'sentiment_analyzer', 'classifier', 'review_analyzer', 'researcher', 'trend_researcher', 'competitor_profiler', 'orchestrator']],
            ['ollama_tag' => 'qwen3:4b',         'display_name' => 'Qwen3 4B',        'category' => 'qa',           'description' => 'Alibaba Qwen3 4B — ново поколение компактен модел с качество близо до старите 7B при двойно по-малко ресурси. Светкавично бърз за QA гейтове, прости проверки и форматиране. Препоръчан основен QA верификатор.',                       'strengths' => ['fast', 'qa', 'structured_tasks', 'multilingual'],     'ram_required_gb' => 4.0,  'size_mb' => 2600,  'is_default_for' => ['qa_verifier', 'publisher']],
            ['ollama_tag' => 'qwen3:8b',         'display_name' => 'Qwen3 8B',        'category' => 'json',         'description' => 'Alibaba Qwen3 8B — наследникът на qwen2.5:7b с по-силен reasoning, по-добра кирилица и стабилен structured output. Отличен баланс скорост/качество за research, извличане на данни и pipeline задачи. Препоръчан planner модел за 8 GB VRAM карти.', 'strengths' => ['structured_tasks', 'reasoning', 'multilingual', 'cyrillic'], 'ram_required_gb' => 6.0,  'size_mb' => 5200,  'is_default_for' => ['keyword_extractor', 'hashtag_generator', 'data_extractor', 'formatter', 'researcher', 'content_en']],
            ['ollama_tag' => 'qwen3:14b',        'display_name' => 'Qwen3 14B',       'category' => 'json',         'description' => 'Alibaba Qwen3 14B — новият флагман под 10 GB: значително по-добър reasoning и structured output от qwen2.5:14b при същия размер. Топ избор за анализи, оркестрация, доклади и ЛОКАЛНО ПЛАНИРАНЕ на агенти (OLLAMA_PLANNER_MODEL). На 8 GB VRAM ще прелива към CPU — там ползвай qwen3:8b.', 'strengths' => ['structured_tasks', 'reasoning', 'powerful', 'cyrillic', 'thinking'], 'ram_required_gb' => 11.0, 'size_mb' => 9300,  'is_default_for' => ['analyzer', 'decision', 'swot_builder', 'sentiment_analyzer', 'classifier', 'review_analyzer', 'researcher', 'trend_researcher', 'competitor_profiler', 'orchestrator', 'report_writer', 'summarizer']],

            // Reasoning / Analysis
            ['ollama_tag' => 'deepseek-r1:8b',   'display_name' => 'DeepSeek-R1 8B',  'category' => 'reasoning',    'description' => 'DeepSeek-R1 с chain-of-thought reasoning — моделът "мисли" на глас преди да отговори. Видимите стъпки на разсъждение правят изводите прозрачни и проверими. Компактен вариант за анализи и вземане на решения при ограничен RAM.',           'strengths' => ['reasoning', 'analysis', 'chain_of_thought'],          'ram_required_gb' => 5.0,  'size_mb' => 4900,  'is_default_for' => ['analyzer', 'decision']],
            ['ollama_tag' => 'phi4',             'display_name' => 'Phi-4 14B',        'category' => 'reasoning',    'description' => 'Microsoft Phi-4 с 14B параметъра постига резултати на по-големи модели благодарение на висококачествени training данни. Отличен reasoning при само 9 GB RAM — ефективен избор когато ресурсите са ограничени, но качеството е важно.',                       'strengths' => ['reasoning', 'efficient'],                             'ram_required_gb' => 9.0,  'size_mb' => 8500,  'is_default_for' => ['analyzer', 'decision', 'summarizer']],
            ['ollama_tag' => 'deepseek-r1:14b', 'display_name' => 'DeepSeek-R1 14B',  'category' => 'reasoning',    'description' => 'Балансираният DeepSeek-R1 модел — по-мощен от 8B, по-достъпен от 32B. Изчерпателно chain-of-thought reasoning при 11 GB RAM. Препоръчан като основен reasoning модел за повечето production flows.',                          'strengths' => ['reasoning', 'chain_of_thought', 'powerful'],          'ram_required_gb' => 11.0, 'size_mb' => 9000,  'is_default_for' => ['analyzer', 'decision', 'researcher', 'trend_researcher']],
            ['ollama_tag' => 'phi4-reasoning',  'display_name' => 'Phi-4 Reasoning',  'category' => 'reasoning',    'description' => 'Microsoft Phi-4 Reasoning — специализирана версия, финно настроена изцяло за reasoning задачи. Съперничи на модели 2-3 пъти по-големи в бенчмаркове за логика и планиране. Идеален за вземане на решения при ограничени GPU ресурси.',   'strengths' => ['reasoning', 'specialized', 'efficient'],             'ram_required_gb' => 11.0, 'size_mb' => 9100,  'is_default_for' => ['decision', 'analyzer', 'swot_builder']],

            // Code
            ['ollama_tag' => 'deepseek-coder-v2', 'display_name' => 'DeepSeek Coder V2', 'category' => 'code',        'description' => 'Водещ open-source модел за генериране на код — поддържа над 300 езика за програмиране с изключително прецизно разбиране на контекста. Препоръчан по подразбиране за всички задачи, свързани с генериране, преглед и дебъгване на код.',                                              'strengths' => ['code_generation', 'top_coder'],                       'ram_required_gb' => 9.0,  'size_mb' => 8900,  'is_default_for' => ['code']],
            ['ollama_tag' => 'qwen2.5-coder:7b',  'display_name' => 'Qwen2.5 Coder 7B', 'category' => 'code',        'description' => 'Alibaba специализиран coding модел с 7B параметъра. Бърз при генериране на boilerplate код и кратки функции. Добър избор когато скоростта е важна — SQL заявки, HTML шаблони, прости скриптове.',                                               'strengths' => ['code_generation', 'fast'],                            'ram_required_gb' => 5.0,  'size_mb' => 4700,  'is_default_for' => ['code']],
            ['ollama_tag' => 'qwen2.5-coder:14b', 'display_name' => 'Qwen2.5 Coder 14B', 'category' => 'code',       'description' => 'Най-популярният open-source code модел (над 16 млн. изтегляния). С 14B параметъра предоставя отличен code reasoning — разбира архитектурата на проекта, рефакторира и обяснява сложен код. Топ избор за code review и сложни задачи.',             'strengths' => ['code_generation', 'code_reasoning', 'popular'],       'ram_required_gb' => 11.0, 'size_mb' => 9000,  'is_default_for' => ['code']],

            // Multilingual
            ['ollama_tag' => 'aya-expanse:8b',   'display_name' => 'Aya Expanse 8B',   'category' => 'multilingual', 'description' => 'Подобрената версия на Aya с разширени езикови способности. Препоръчана замяна на оригиналния Aya 8B за по-качествени преводи и по-естествен текст на не-английски езици. Текущ препоръчан translator модел.',                                                    'strengths' => ['multilingual', 'improved_aya'],                       'ram_required_gb' => 5.0,  'size_mb' => 4700,  'is_default_for' => ['translator']],

            // Vision
            ['ollama_tag' => 'llama3.2-vision:11b', 'display_name' => 'LLaMA 3.2 Vision 11B', 'category' => 'vision', 'description' => 'Meta LLaMA 3.2 Vision с 11B параметъра — най-добрият multilingual vision модел в класа. Разбира текст в изображения на множество езици, анализира диаграми и документи. Препоръчан за production vision задачи.',               'strengths' => ['vision', 'meta', 'high_quality'],  'ram_required_gb' => 8.0,  'size_mb' => 7900,  'is_default_for' => ['image_describer', 'vision']],
            ['ollama_tag' => 'qwen2.5vl:7b',        'display_name' => 'Qwen2.5 VL 7B',        'category' => 'vision', 'description' => 'Alibaba Qwen2.5 Vision-Language 7B — специализиран за OCR, документно разбиране и извличане на структурирани данни от изображения. Текущ препоръчан модел за image_describer задачи поради отличния му document understanding.', 'strengths' => ['vision', 'ocr', 'document_understanding'], 'ram_required_gb' => 7.0, 'size_mb' => 5000, 'is_default_for' => ['image_describer']],
        ];

        foreach ($models as $model) {
            LlmModel::updateOrCreate(
                ['ollama_tag' => $model['ollama_tag']],
                $model
            );
        }

        // Каталогът е истината: модели, отпаднали от списъка по-горе (остарели
        // поколения), се махат и от базата, за да не ги предлага UI-ят/селекторът.
        LlmModel::whereNotIn('ollama_tag', array_column($models, 'ollama_tag'))->delete();
    }
}
