<?php

return [
    'langs' => [
        'bg' => 'Български',
        'en' => 'English',
        'de' => 'Deutsch',
        'fr' => 'Français',
        'es' => 'Español',
        'ru' => 'Русский',
    ],

    'tones' => [
        'Neutral' => 'Неутрален',
        'Friendly' => 'Приятелски',
        'Formal' => 'Официален',
        'Cold' => 'Дистанциран',
        'Analytical' => 'Аналитичен',
        'Creative' => 'Креативен',
        'Ironic' => 'Ироничен',
        'Persuasive' => 'Убедителен',
        'Empathetic' => 'Емпатичен',
        'Authoritative' => 'Авторитетен',
        'Warm' => 'Топъл',
        'Concise' => 'Кратък',
        'Inspirational' => 'Вдъхновяващ',
        'Playful' => 'Игрив',
        'Diplomatic' => 'Дипломатичен',
        'Urgent' => 'Спешен',
        'Educational' => 'Образователен',
        'Confident' => 'Уверен',
    ],

    'styles' => [
        'Professional' => 'Професионален',
        'Academic' => 'Академичен',
        'Creative' => 'Креативен',
        'Critical' => 'Критичен',
        'Journalistic' => 'Журналистически',
        'Conversational' => 'Разговорен',
        'Technical' => 'Технически',
        'Narrative' => 'Разказвателен',
        'Minimalist' => 'Минималистичен',
        'Descriptive' => 'Описателен',
        'Instructional' => 'Инструктивен',
        'Storytelling' => 'Сторителинг',
        'SEO' => 'SEO',
        'Sales' => 'Продажбен',
        'Step-by-step' => 'Стъпка по стъпка',
        'Comparative' => 'Сравнителен',
        'Executive' => 'За мениджмънт',
        'Accessible' => 'Достъпен',
    ],

    'formats' => [
        'Report' => 'Доклад',
        'Blog post' => 'Блог статия',
        'Brochure' => 'Брошура',
        'Proposal' => 'Предложение',
        'Email' => 'Имейл',
        'Social media post' => 'Пост за социални мрежи',
        'Press release' => 'Прессъобщение',
        'Newsletter' => 'Бюлетин',
        'Product description' => 'Продуктово описание',
        'Executive summary' => 'Резюме за ръководство',
        'FAQ' => 'Често задавани въпроси',
        'Listicle' => 'Списък статия',
        'Case study' => 'Казус',
        'Landing page' => 'Лендинг страница',
        'Ad copy' => 'Рекламен текст',
        'Script' => 'Сценарий',
        'Checklist' => 'Чеклист',
        'Comparison table' => 'Сравнителна таблица',
        'How-to guide' => 'Практическо ръководство',
        'White paper' => 'White paper',
        'Presentation outline' => 'Структура за презентация',
    ],
];
